# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74c6fbbe71e5c72c76b1270beea5a54fbfd12b2058a405b5ba13d42913eb20272037daccbd1be583495347404ad60d0ee0c9996929672cd809f0f5f73e5f97c

test:
  secret_key_base: d6192f236b03f4e8af17d54128a5e419c25a9fd6c6b8d74674dbc407599f59f2a66b4e20e2a990cede9b3e9248ebd265bc28c71733616fdf20e83bf081882612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
